### ISSUE TITLE
How multi-scale loss is incorporated?

### ISSUE THREAD

**Issue by sayakpaul** [Charlie0215/AWNet-Attentive-Wavelet-Network-for-Image-ISP#8]
Hi authors. 

Thanks for your hard work. As per the paper, the network is trained in a multi-scale manner. Currently, I am unable to understand how that is incorporated. Could you point me to a helpful code block that demonstrates the multi-scale training?

**Comment by Charlie0215** [comment]
Thanks for your comment. Please refer to line 60 in loss.py where we calculate loss on different scales.
